#服务器配置
[server]
port=8080
host="http://127.0.0.1"

#Mysql配置
[mysql]
port=3306
host="127.0.0.1"
#连接mysql的用户
user="root"
#数据库密码
password="root"
#数据库名称
database="tiktok"

#Redis配置
[redis]
port=6379
host="127.0.0.1"

